name: activite2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

flutter:
  assets:
    - assets/sunrise1.jpg
    - assets/sunrise2.jpg
    - assets/sunrise3.jpg
